name: CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo ${{ toJson(github) }}
    - name: Check PR labels action step
      id: check_pr_labels
      uses: shioyang/check-pr-labels-on-push-action@v1.0.3
    - name: See result
      run: echo "${{ steps.check_pr_labels.outputs.result }}"

